// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVXMkNGsM-VOh_vrvqrkzhzbqTpyGjlO8',
    appId: '1:748356573080:web:c9830dd5810f925166fded',
    messagingSenderId: '748356573080',
    projectId: 'verified-student-network-155e2',
    authDomain: 'verified-student-network-155e2.firebaseapp.com',
    storageBucket: 'verified-student-network-155e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-T-BwccMfXgohff8w-yBkghD5Byv5jUk',
    appId: '1:748356573080:android:e63b50bd482006a166fded',
    messagingSenderId: '748356573080',
    projectId: 'verified-student-network-155e2',
    storageBucket: 'verified-student-network-155e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzsVqOPv0zrlq0ouOHIsVzjxPACMmoTaw',
    appId: '1:748356573080:ios:c0e84f35fdaef47866fded',
    messagingSenderId: '748356573080',
    projectId: 'verified-student-network-155e2',
    storageBucket: 'verified-student-network-155e2.appspot.com',
    iosBundleId: 'com.example.verifiedStudentNetwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzsVqOPv0zrlq0ouOHIsVzjxPACMmoTaw',
    appId: '1:748356573080:ios:c0e84f35fdaef47866fded',
    messagingSenderId: '748356573080',
    projectId: 'verified-student-network-155e2',
    storageBucket: 'verified-student-network-155e2.appspot.com',
    iosBundleId: 'com.example.verifiedStudentNetwork',
  );
}
