// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUvJGHeLmGQQyRL62gpLh-lClxc-whVYo',
    appId: '1:280964607056:web:4fa176fb5f9ca049c6b555',
    messagingSenderId: '280964607056',
    projectId: 'verified-student-network',
    authDomain: 'verified-student-network.firebaseapp.com',
    databaseURL: 'https://verified-student-network-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'verified-student-network.appspot.com',
    measurementId: 'G-NWFDJ7EJCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmyDEKGZEbKd3B_aOlCfWSj_joApYRvaY',
    appId: '1:280964607056:android:bf89b66195fd1d95c6b555',
    messagingSenderId: '280964607056',
    projectId: 'verified-student-network',
    databaseURL: 'https://verified-student-network-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'verified-student-network.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAreR9EX3sHSzaQo1nGFygMxMVgMVETkI',
    appId: '1:280964607056:ios:120e7b2bee8f8305c6b555',
    messagingSenderId: '280964607056',
    projectId: 'verified-student-network',
    databaseURL: 'https://verified-student-network-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'verified-student-network.appspot.com',
    iosClientId: '280964607056-mkmvhq4275h529s792cl0kg1aqju7avn.apps.googleusercontent.com',
    iosBundleId: 'com.example.verifiedStudentNetwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAreR9EX3sHSzaQo1nGFygMxMVgMVETkI',
    appId: '1:280964607056:ios:120e7b2bee8f8305c6b555',
    messagingSenderId: '280964607056',
    projectId: 'verified-student-network',
    databaseURL: 'https://verified-student-network-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'verified-student-network.appspot.com',
    iosClientId: '280964607056-mkmvhq4275h529s792cl0kg1aqju7avn.apps.googleusercontent.com',
    iosBundleId: 'com.example.verifiedStudentNetwork',
  );
}
